### ISSUE TITLE
Untag old ZE, tag new Mezzio and publish

### ISSUE THREAD

**Issue by Slamdunk** [Codeception/module-mezzio#2]
Hi, while copying the library from `module-zendexpressive` the old tags were also transferred:

![immagine](https://user-images.githubusercontent.com/152236/76058468-cc83e200-5f7c-11ea-9c56-68f52d38b324.png)

I propose to:

1. Remove those tags, so if ever some user types `composer require zendframework/zend-expressive codeception/module-mezzio` the command would fail instead of silently install the old `codeception/module-zendexpressive` source
1. Tag a `v2` version to be clear about the change
1. Publish this of packagist

**Comment by Naktibalda** [comment]
https://packagist.org/packages/codeception/module-mezzio

**Comment by Slamdunk** [comment]
Thank you very much for accepting me as a Collaborator
